[package]
name = "tar-downloader"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.22"
reqwest = { version = "0.11.10", features = ["blocking"] }
tar = "0.4.38"
